apiVersion: apps/v1
kind: Deployment
metadata:
  name: gim-app
  labels:
    app: gim-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gim-app
  template:
    metadata:
      labels:
        app: gim-app
    spec:
      containers:
      - name: gim-app
        image: luissssmartins/gim-app
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
      imagePullSecrets:
      - name: regcred