name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir a imagem Docker
        run: |
          docker build -t luissssmartins/gim-app:latest .
          docker tag luissssmartins/gim-app:latest luissssmartins/gim-app:${{ github.sha }}

      - name: Enviar a imagem para o Docker Hub
        run: |
          docker push luissssmartins/gim-app:latest
          docker push luissssmartins/gim-app:${{ github.sha }}